{
 "title": "UMStor Processes",
 "description": "Process metrics exported by https://github.com/ncabatoff/process-exporter.",
 "tags": [ "OS" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "processes",
    "query": "label_values(namedprocess_namegroup_num_procs,groupname)"
   },
   {
    "name": "node",
    "query": "label_values(namedprocess_namegroup_cpu_system_seconds_total,instance)"
   },
   {
    "name": "port",
    "query": "label_values(namedprocess_namegroup_cpu_system_seconds_total,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "num processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{groupname=~\"$processes\",instance=~\"$node:$port\"}",
     "legendFormat": "{{instance}} {{groupname}}"
    },
    {
     "expr": "namedprocess_namegroup_num_threads{groupname=~\"$processes\",instance=~\"$node:$port\"}",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_cpu_system_seconds_total{groupname=~\"$processes\",instance=~\"$node:$port\"}[$interval])",
     "legendFormat": "cpu_sys {{instance}}  {{groupname}}"
    },
    {
     "expr": "rate(namedprocess_namegroup_cpu_user_seconds_total{groupname=~\"$processes\",instance=~\"$node:$port\"}[$interval])",
     "legendFormat": "cpu_user {{instance}}  {{groupname}}"
    }
   ]
  },
  {
   "title": "read bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_read_bytes_total{groupname=~\"$processes\",instance=~\"$node:$port\"}[$interval])",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  },
  {
   "title": "write bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(namedprocess_namegroup_write_bytes_total{groupname=~\"$processes\",instance=~\"$node:$port\"}[$interval])",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  },
  {
   "title": "resident memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"resident\",instance=~\"$node:$port\"}",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  },
  {
   "title": "virtual memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{groupname=~\"$processes\", memtype=\"virtual\",instance=~\"$node:$port\"}",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "dateTimeAsIso" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_oldest_start_time_seconds{groupname=~\"$processes\",instance=~\"$node:$port\"} * 1000",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  },
  {
   "title": "Open FileDesc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "namedprocess_namegroup_open_filedesc{groupname=~\"$processes\",instance=~\"$node:$port\"}",
     "legendFormat": "{{instance}} {{groupname}}"
    }
   ]
  }
 ]
}